### ISSUE TITLE
第三章 页表的进程地址空间处 翻译问题

### ISSUE THREAD

**Issue by mag1cianag** [shzhxh/xv6-riscv-book-CN#1]
我们可以看到页表有如下好处：1，不同的页表把用户空间映射到不同的物理内存上，这样每个进程都有各自的用户空间。2，从进程的角度看虚拟地址是连续的，但实际上它所对应的虚拟地址却不必是连续的。

应该是对应的物理地址不必连续.

感谢作者无私翻译

**Comment by shzhxh** [comment]
已修正，感谢！
